auth_enabled: false

server:
  http_listen_port: 3100

common:
  path_prefix: /mnt/auto/loki-data
  storage:
    filesystem:
      chunks_directory: /mnt/auto/loki-data/chunks
      rules_directory: /mnt/auto/loki-data/rules
  replication_factor: 1
  ring:
    kvstore:
      store: inmemory

storage_config:
  index_queries_cache_config:
    redis:
      endpoint: 10.20.133.149:6379
      password: Aa123456
      expiration: 1h
      timeout: 1000ms

chunk_store_config:
  chunk_cache_config:
    redis:
      endpoint: 10.20.133.149:6379
      password: Aa123456
      expiration: 1h
      timeout: 1000ms
  write_dedupe_cache_config:
    redis:
      endpoint: 10.20.133.149:6379
      password: Aa123456
      expiration: 1h
      timeout: 1000ms

query_range:
  results_cache:
    cache:
      embedded_cache:
        enabled: true
        max_size_mb: 100

schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

ruler:
  alertmanager_url: http://localhost:9093

# By default, Loki will send anonymous, but uniquely-identifiable usage and configuration
# analytics to Grafana Labs. These statistics are sent to https://stats.grafana.org/
#
# Statistics help us better understand how Loki is used, and they show us performance
# levels for most users. This helps us prioritize features and documentation.
# For more information on what's sent, look at
# https://github.com/grafana/loki/blob/main/pkg/usagestats/stats.go
# Refer to the buildReport method to see what goes into a report.
#
# If you would like to disable reporting, uncomment the following lines:
#analytics:
#  reporting_enabled: false
